name: Codecov coverage report 

on:
  push:
    branches: [ master, release ] 
  pull_request:

jobs:
  codecov:
    runs-on: ubuntu-latest

    env:
      MAINNET_MNEMONIC: ${{ secrets.MAINNET_MNEMONIC }}
      MAINNET_URI: ${{ secrets.MAINNET_URI }}
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
      TEST_URI: ${{ secrets.TEST_URI }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci 

      - name: Generate coverage report 
        run: npm run coverage 

      - name: Report coverage
        uses: codecov/codecov-action@v2
        with:
          name: knox-contracts-tests 
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          files: coverage-final.json
          fail_ci_if_error: true
          verbose: true
