name: Lint validation 
on:
  push:
    branches: [ master, release ] 
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci 

      - name: Lint Solidity 
        run: npm run lint:sol

      - name: Lint Typescript 
        run: npm run lint:ts
